version: '3.3'
services:
  db:
    image: 'msql:latest'
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'jacon'
      MYSQLPASSWORD: 'senha'
      MYSQL_ROOT_PASSWORD: 'senharoot'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: